Storybook main menu
credix-finance/credix-app-v2 pull request #15
Opened 2022-02-11 09:11 UTC by BartDeCaluwe

This PR will add:

- CredixLogo component that can render a dark or light version of the logo depending on either `prefers-color-scheme` or by passing a prop. 
- WalletButton component that can launch the `@solana/wallet-adapter-react` modal. With a dropdown to: copy address, change wallet, disconnect. 
- MainMenu component that displays the CredixLogo and WalletButton components

2022-02-14 14:18 UTC, BouweCeunen commented
I don't see 2 stories of the CredixLogo on storybook if I click on `Docs`, but I also don't see anything out of the ordinary in the code itself, maybe I'm overlooking something?

2022-02-14 14:28 UTC, BartDeCaluwe commented
> I don't see 2 stories of the CredixLogo on storybook if I click on `Docs`, but I also don't see anything out of the ordinary in the code itself, maybe I'm overlooking something?

Not sure what you mean with `Docs`. But the CredixLogo can be seen here: https://c696eb6d.credix-app-v2.pages.dev/?path=/story/credixlogo--light

2022-02-15 10:54 UTC, RuvenSalamon commented
![image](https://user-images.githubusercontent.com/14349484/154047771-3d12eb48-9193-4efa-bdf9-b2690e82c5ec.png)
![image](https://user-images.githubusercontent.com/14349484/154047938-9d50d74a-a810-461b-8b08-9e27c6ecf711.png)
there is some misalignment here

2022-02-15 13:24 UTC, RuvenSalamon commented
one commit has 'cleanup' as tag. this is not specified in our git guidelines. maybe we can use refactor here?
if we feel like as a team we need additional tags we can always discuss it of course. I do want to prevent a jungle of commit tags as that would defeat part of the purpose

2022-02-15 13:24 UTC, RuvenSalamon requested changes

2022-02-15 13:24 UTC, RuvendeGroote commented on src/components/WalletButton.tsx
> +	const [dropdownVisible, setDopdownVisible] = useState(false);
Dopdown

2022-02-15 13:25 UTC, RuvenSalamon commented
your latest feat commit is a good example of something that could be included in another commit with rebase interactive

2022-02-15 13:28 UTC, BartDeCaluwe commented
> one commit has 'cleanup' as tag. this is not specified in our git guidelines. maybe we can use refactor here? if we feel like as a team we need additional tags we can always discuss it of course. I do want to prevent a jungle of commit tags as that would defeat part of the purpose

Yes, my bad. I don't think `refactor` is a good candidate in that scenario. No functionality was rewritten, only some unused css was removed. 
Unless we agree that we bundle cleanup under the `refactor` tag which is fine by me.

2022-02-15 16:05 UTC, RuvenSalamon approved these changes

2022-02-15 16:38 UTC, BouweCeunen approved these changes

2022-02-15 16:40 UTC, merged