Cicd file cleanup
credix-finance/credix-app-v2 pull request #150
Opened 2022-05-06 13:47 UTC by BartDeCaluwe

This PR will:

- list the inline env vars on multiple lines instead of one line
- convert the file indentation mode from spaces to tabs

*List which issues are fixed by this PR. You must list at least one issue.*
Managing env vars and secrets will be much easier and less error prone.

## Checklist

- [ ] I used the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
- [ ] Unit tests have been created if a new feature was added.
- [ ] Translations have been added and extracted if a new feature was added.

2022-05-09 08:39 UTC, BouweCeunen approved these changes, later dismissed

2022-05-24 18:11 UTC, RuvenSalamon requested changes

2022-05-24 18:11 UTC, RuvenSalamon commented on .github/workflows/cicd.yaml
>  on:
I think you accidentally added tabs everywhere

2022-06-03 11:08 UTC, RuvenSalamon requested changes

2022-06-03 11:08 UTC, RuvenSalamon commented on .github/workflows/cicd.yaml
> +					NEXT_PUBLIC_GOOGLE_ANALYTICS=${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}
tabs

2022-06-08 09:38 UTC, RuvenSalamon approved these changes

2022-06-08 13:41 UTC, merged