Amortization calculation
credix-finance/credix-app-v2 pull request #159
Opened 2022-05-17 10:39 UTC by BartDeCaluwe

*Replace this paragraph with a description of what this PR is changing or adding, and why.*

*List which issues are fixed by this PR. You must list at least one issue.*

## Checklist

- [ ] I used the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
- [ ] Unit tests have been created if a new feature was added.
- [ ] Translations have been added and extracted if a new feature was added.

2022-05-20 09:44 UTC, BouweCeunen commented on src/utils/amortization.utils.ts
> +	}
Can these two things ever happen? Shouldn't we always pass valid values to this method?

2022-05-20 09:44 UTC, BouweCeunen approved these changes

2022-05-25 12:09 UTC, RuvenSalamon requested changes

2022-05-25 12:09 UTC, RuvendeGroote commented on src/utils/amortization.utils.ts
> +	if (!rate) {
rate can't be undefined or null according to the function signature

2022-05-25 12:09 UTC, RuvendeGroote commented on src/utils/amortization.utils.ts
> +	if (!numberOfPayments) {
same here

2022-05-25 12:09 UTC, RuvendeGroote commented on src/utils/amortization.utils.ts
> +	rate: Ratio,
We never use the term rate in the program or client. we should guard the domain lingo across projects so we should use interest or interestPercentage. I do think that interestRate is the more appropriate term for what we are doing and I have noted that we should move the lingo towards using interestRate eventually.

2022-05-25 12:09 UTC, RuvenSalamon commented on src/utils/amortization.utils.ts
> +export const calculateMonthlyPayment = (
add the relevant formulas from this page as comments https://www.investopedia.com/terms/a/amortization.asp#:~:text=How%20to%20Calculate%20Amortization%20of%20Loans&text=You'll%20need%20to%20divide,your%20loan%20term%20by%2012 and have the code reflect them.

2022-06-06 10:41 UTC, RuvenSalamon approved these changes

2022-06-08 11:57 UTC, merged