Bullet calculation
credix-finance/credix-app-v2 pull request #160
Opened 2022-05-17 10:40 UTC by BartDeCaluwe

*Replace this paragraph with a description of what this PR is changing or adding, and why.*

*List which issues are fixed by this PR. You must list at least one issue.*

## Checklist

- [ ] I used the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
- [ ] Unit tests have been created if a new feature was added.
- [ ] Translations have been added and extracted if a new feature was added.

2022-05-20 11:21 UTC, BouweCeunen approved these changes

2022-05-27 08:49 UTC, RuvenSalamon commented on src/utils/bullet.utils.ts
> +export const calculateMonthlyPayment = (principal: number, rate: Ratio, paymentPeriods: number) => {
in the client we use 

```
export interface BulletLoanPeriodsGenerationConfig {
	principal: number;
	interest: Fraction;
	totalRepayments: number;
}

export const generateBulletLoanPeriods = (
	config: BulletLoanPeriodsGenerationConfig
): RepaymentPeriodConfig[] => {
	const interest = config.interest.apply(config.principal).toNumber();

	return Array(config.totalRepayments - 1)
		.fill(0)
		.map(() => ({
			principal: 0,
			interest,
		}))
		.concat({ principal: config.principal, interest });
};
```
for generating bullet loans. it's a lot more concise. (still rudimentary as it just keeps the decimals but that also happens here).
this interface and method are already exposed in the client so we can just use those

2022-06-08 13:22 UTC, RuvendeGroote requested changes

2022-06-08 13:22 UTC, RuvendeGroote commented on src/consts.ts
> +export const defaultTranches = [
seems unused

2022-06-08 14:57 UTC, RuvenSalamon approved these changes

2022-06-08 15:08 UTC, merged