Create new deal details
credix-finance/credix-app-v2 pull request #161
Opened 2022-05-17 10:40 UTC by BartDeCaluwe

*Replace this paragraph with a description of what this PR is changing or adding, and why.*

*List which issues are fixed by this PR. You must list at least one issue.*

## Checklist

- [ ] I used the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
- [ ] Unit tests have been created if a new feature was added.
- [ ] Translations have been added and extracted if a new feature was added.

2022-05-27 11:56 UTC, RuvenSalamon commented
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/14349484/170694751-4cffd5b7-4d7d-4849-8de5-4ceda0fd0e27.png">
I have noticed some visual regression. not sure if it's because of this PR

2022-05-30 09:09 UTC, RuvenSalamon requested changes

2022-05-30 09:09 UTC, RuvendeGroote commented on src/components/AmortizationRepaymentSchedule.tsx
> +	repaymentPeriod: number;
should be plural

2022-05-30 09:09 UTC, RuvendeGroote commented on src/components/AmortizationRepaymentSchedule.tsx
> +			const schedule = repaymentSchedule(principal, financingFeeRatio, repaymentPeriod);
I don't really like that this has the same name for bullet loans and amortization loans. it's not really apparent that we are using the wrong one unless you check the imports (which most people don't). anyways, not a big deal ig as the schedule generation is moving to the client

2022-05-30 09:09 UTC, RuvendeGroote commented on src/utils/format.utils.ts
> +export const currencyFormatter = Intl.NumberFormat("en", {
what is your opinion on renaming the numberFormatter to something like compactformatter? for me it was confusing why we had two seemingly similar functions (made sense when I saw how they were used though)

2022-05-30 09:09 UTC, RuvendeGroote commented on src/components/SelectorCard.tsx
> +	selectCard?: () => void;
I prefer 'on{action}' names for click/event handlers

2022-05-30 09:09 UTC, RuvendeGroote commented on src/components/SelectorCard.tsx
> +		<div className={classes} onClick={selectCard}>
we have an onClick on the outer div that will still trigger even if it's `isDisplay`. is this behaviour we want? I can imagine if we say it is display only that we don't want to make it interactable

2022-05-30 09:09 UTC, RuvendeGroote commented on src/components/SelectorCard.tsx
> +	isDisplay,
I prefer displayOnly or interactive or something

2022-05-30 09:09 UTC, RuvenSalamon commented on src/components/RepaymentScheduleTable.tsx
> +			title: "Date",
use intl

2022-05-30 09:09 UTC, RuvenSalamon commented on src/components/RepaymentScheduleTable.tsx
>  	dataSource: AntdTableProps<any>["dataSource"];
we don't have to use any here as we know the dataSource type

2022-06-02 08:55 UTC, BartDeCaluwe commented
> <img alt="image" width="1287" src="https://user-images.githubusercontent.com/14349484/170694751-4cffd5b7-4d7d-4849-8de5-4ceda0fd0e27.png">
> I have noticed some visual regression. not sure if it's because of this PR

fixed in: https://github.com/credix-finance/credix-app-v2/pull/148

2022-06-02 09:03 UTC, BartDeCaluwe commented on src/components/AmortizationRepaymentSchedule.tsx
> +			const schedule = repaymentSchedule(principal, financingFeeRatio, repaymentPeriod);
Yes totally agree. I wasn't too happy about it myself.

2022-06-02 09:21 UTC, BartDeCaluwe commented on src/utils/format.utils.ts
> +export const currencyFormatter = Intl.NumberFormat("en", {
We can def do that. `numberFormatter` is very generic for what it actually does.

2022-06-06 10:43 UTC, RuvenSalamon commented on src/utils/repayment.utils.ts
> +		(acc, repayment, index) => {
can we put these in types?

2022-06-08 13:16 UTC, RuvenSalamon requested changes

2022-06-08 13:16 UTC, RuvendeGroote commented on src/utils/repayment.utils.ts
> +		(acc, repayment, index) => {
can we put these in types?

2022-06-08 13:16 UTC, RuvendeGroote commented on src/components/DealForm.tsx
> +			await form.validateFields(fieldsToValidate);
`await form.validateFields(fieldsToValidate).then(() => setCurrentStep(nextStep))`

2022-06-08 13:16 UTC, RuvendeGroote commented on src/components/DealForm.tsx
> +			await form.validateFields(fieldsToValidate);
no try empty catch needed

2022-06-08 13:16 UTC, RuvendeGroote commented on src/components/AmortizationRepaymentSchedule.tsx
>  						<Button onClick={() => setShowTable(!showTable)} type="text">
this is duplicate in both schedules

2022-06-08 13:16 UTC, RuvendeGroote commented on src/components/AmortizationRepaymentSchedule.tsx
>  	return (
this component is duplicate except for the input and the logic

2022-06-08 13:16 UTC, RuvendeGroote commented on src/utils/amortization.utils.ts
> +	if (!rate) {
rate is always present according to the function.

2022-06-08 13:16 UTC, RuvendeGroote commented on src/utils/amortization.utils.ts
> +	if (!numberOfPayments) {
same here

2022-06-08 13:16 UTC, RuvenSalamon commented on src/consts.ts
> +export const defaultTranches = [
this seems unused

2022-06-08 13:16 UTC, RuvendeGroote commented on package.json
> +		"@credix/credix-client": "^0.1.0",
is this the correct client?

2022-06-14 09:02 UTC, RuvenSalamon approved these changes

2022-06-14 09:09 UTC, merged