docs: update docs
credix-finance/credix-app-v2 pull request #185
Opened 2022-06-24 15:56 UTC by BartDeCaluwe

This pr will add the following changes to the readme:

- add a setup and installation section
- add more info about the clusters
- update the setup instructions for a local cluster
- update the recommended way of tagging messages
- add information about antdesign and charts
- add information about tailwind
- fix the names of the different clusters

*List which issues are fixed by this PR. You must list at least one issue.*

## Checklist

- [ ] I used the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
- [ ] Unit tests have been created if a new feature was added.
- [ ] Translations have been added and extracted if a new feature was added.

2022-06-28 09:00 UTC, RuvenSalamon commented
can you add an explanation to the classNames util? (maybe go over the code and look at what might be confusing later on. imagine an average intelligence developer that knows react looking at the code)

2022-06-28 09:44 UTC, RuvenSalamon commented
extract the .env.local.dist part to a separate section on how to configure the app. mention that further explanation can be found in the .env.local.dist file. add explanations in that file.

2022-06-28 09:48 UTC, RuvenSalamon commented
mention typeform and how you can get past it.

2022-06-28 09:48 UTC, RuvenSalamon requested changes

2022-06-28 09:48 UTC, RuvenSalamon commented on README.md
>  Maximum amount of data per 30 second: 100 MB
maybe it's better to just explain different clusters and refer to https://docs.solana.com/cluster/rpc-endpoints. mention that pre-mainnet lives on devnet as well.

2022-07-18 08:42 UTC, BartDeCaluwe commented
> mention typeform and how you can get past it.

Is this still relevant? When we add the Markets, the typeform buttons will be moved to a less prominent space.

2022-07-18 10:59 UTC, RuvenSalamon commented
> > mention typeform and how you can get past it.
> 
> Is this still relevant? When we add the Markets, the typeform buttons will be moved to a less prominent space.

no

2022-07-21 19:36 UTC, RuvenSalamon approved these changes

2022-07-22 06:54 UTC, merged