fix: max tranche investment amount calculation
credix-finance/credix-app-v2 pull request #186
Opened 2022-06-24 15:58 UTC by BartDeCaluwe

This PR will:

- fix the max tranche investment amount calculation

## Checklist

- [ ] I used the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
- [ ] Unit tests have been created if a new feature was added.
- [ ] Translations have been added and extracted if a new feature was added.

2022-06-28 09:49 UTC, RuvenSalamon requested changes, later dismissed

2022-06-28 09:49 UTC, RuvenSalamon commented on src/components/InvestInTranche.tsx
> +		userBaseBalance.uiAmount,
avoid using the uiAmount for calculations.

2022-07-05 11:48 UTC, MaximPiessen approved these changes

2022-07-05 12:08 UTC, MaximPiessen approved these changes

2022-07-05 12:08 UTC, merged