Advanced settings
credix-finance/credix-app-v2 pull request #202
Opened 2022-07-04 08:11 UTC by BartDeCaluwe

This PR will:

- add a drawer component to the new deal form where you can enable/disable advanced settings
- display the advanced settings on the deal review page
- reworked the review deal page so it is inline with the updated design
- added the advanced settings to the deal show page

## Checklist

- [ ] I used the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
- [ ] Unit tests have been created if a new feature was added.
- [ ] Translations have been added and extracted if a new feature was added.

2022-07-06 14:04 UTC, MaximPiessen commented
Can we have some more margin after each section? Now it's a bit messy / not clear which content belongs to a title or not. + what will we do with longer titles? 

![Screenshot 2022-07-06 at 16 03 23](https://user-images.githubusercontent.com/31801298/177569122-52c5188e-808f-4009-a473-155db0d193cc.png)

2022-07-14 14:37 UTC, RuvenSalamon requested changes

2022-07-14 14:37 UTC, RuvendeGroote commented on src/components/DealDetailsStep.tsx
> +				<Drawer
I prefer it when we create small components. This is an AdvancedSettingsDrawer to me and could/should be a separate component

2022-07-18 09:27 UTC, RuvenSalamon requested changes

2022-07-18 09:27 UTC, RuvenSalamon commented on src/components/DealForm.tsx
> +import { DealAdvancedSettings, defaultAdvancedSettings, threeTrancheStructure } from "@consts";
unused imports. are we not catching those?

2022-07-18 09:27 UTC, RuvenSalamon commented on src/components/Switch.tsx
> +export const Switch: FunctionComponent<SwitchProps> = ({ name, label }) => {
no storybook story?

2022-07-18 09:27 UTC, RuvenSalamon commented on src/components/Icon.tsx
> +		case "adjust":
we haven't been updating the icons in storybook. I wonder if it should be in there

2022-07-18 09:27 UTC, RuvenSalamon commented on src/components/Icon.tsx
> +					fill="currentColor"
but then seeing changes to an older icon makes me think we should have them in there for chromatic

2022-07-18 09:27 UTC, RuvenSalamon commented on src/components/Drawer.tsx
> +export const Drawer: FunctionComponent<DrawerProps> = ({
storybook?

2022-07-18 12:18 UTC, BartDeCaluwe commented on src/components/Icon.tsx
> +					fill="currentColor"
I was normally going to have a meeting with Tim regarding the icon pack we are using. As the current one I feel is not optimal. But it got postponed.
Ideally we use an icon pack where adding them to storybook is not necessary, as they are browsable on a website. And one that doesn't have hardcoded `fill` values that need updating. 

I'll reschedule that meeting this week so that adding the icons to storybook will become obsolete. Unless you have a different opinion/suggestion.

2022-07-19 08:55 UTC, RuvenSalamon commented on src/components/Icon.tsx
> +					fill="currentColor"
no, let's focus on finishing everything this week. keep the meeting postponed but do have it

2022-07-19 08:59 UTC, RuvenSalamon approved these changes

2022-07-19 11:43 UTC, merged