Tranche advanced settings
credix-finance/credix-app-v2 pull request #206
Opened 2022-07-06 10:26 UTC by BartDeCaluwe

This PR will add:

- edit tranche drawer where you can enable/disable early withdrawals for interest and principal
- Advanced tranche settings on the review page
- updated default tranche values

## Checklist

- [x] I used the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
- [ ] Unit tests have been created if a new feature was added.
- [x] Translations have been added and extracted if a new feature was added.

2022-07-18 11:44 UTC, RuvenSalamon commented
conflicts

2022-07-19 10:19 UTC, RuvenSalamon commented
conflicts

2022-07-20 08:37 UTC, RuvenSalamon requested changes
wip review (needed to review something else) but you can already fix the comment

2022-07-20 08:37 UTC, RuvendeGroote commented on src/components/DealForm.tsx
> +	trancheStructure: defaultTranches[defaultTranches.length - 1].value,
the values of these defaultTranches are equal to the trancheSettingsFields
defaulttranches.value is used as the key of a form item at the same time we refer to those form items using the trancheSettingsFields const. I want to unify those.

2022-07-21 11:09 UTC, RuvenSalamon requested changes

2022-07-21 11:09 UTC, RuvendeGroote commented on src/components/FormItem.tsx
> +		labelClassName && !labelClassName.includes("mb-") && "mb-7",
doesn't this always either return mb-7 or falsy?
and why is it not allowed for the label to have a mb- css class?

2022-07-21 11:09 UTC, RuvendeGroote commented on src/components/ReviewDeal.tsx
> +					{intl.formatMessage({
put messages separate

2022-07-21 11:09 UTC, RuvenSalamon commented on src/components/TrancheLine.tsx
> +	structure: TrancheSettings;
rename. these are settings and we also have a tranchestructure type so this is confusing

2022-07-21 11:09 UTC, RuvenSalamon commented on src/components/TrancheLine.tsx
> +					? ratioFormatter.format(Big(apr.toString().replace(",", "")).div(100).toNumber())
not sure if this always works? isn't this dependent on locale? also, can we abstract this as we are doing the same thing multiple times.

2022-07-21 11:09 UTC, RuvenSalamon commented on src/components/TrancheOption.tsx
> +				name: "Senior",
can we have a tranche name enum or something somewhere?

2022-07-21 21:05 UTC, RuvenSalamon commented on src/components/DealForm.tsx
> +	trancheStructure: defaultTranches[defaultTranches.length - 1].value,
was this fixed? I still see us referencing the same form items using different types/variables containing the same hardcoded string values. either eliminate one of them or extract tranche name into an enum or union type and use that. I prefer just extracting anyways as these names are used in many places.

2022-07-21 22:17 UTC, RuvenSalamon requested changes

2022-07-21 22:17 UTC, RuvenSalamon commented on src/consts.ts
>  export const trancheNames = ["super senior", "senior", "mezzanine", "junior"];
replace these values now that we have the enum

2022-07-21 22:17 UTC, RuvenSalamon commented on src/types/tranche.types.ts
> +export enum TrancheName {
this enum can be used everywhere we talk about tranches

2022-07-22 15:24 UTC, RuvenSalamon approved these changes

2022-07-22 15:24 UTC, merged