Edit tranche structure
credix-finance/credix-app-v2 pull request #215
Opened 2022-07-13 11:22 UTC by BartDeCaluwe

This PR will:

- allow users to edit the exisiting tranche structure
- calculate apr, percentage of interest and percentage of principal when the structure is updated

*List which issues are fixed by this PR. You must list at least one issue.*

## Checklist

- [ ] I used the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
- [ ] Unit tests have been created if a new feature was added.
- [ ] Translations have been added and extracted if a new feature was added.

2022-07-20 13:24 UTC, RuvendeGroote requested changes

2022-07-20 13:24 UTC, RuvendeGroote commented on src/components/DealForm.tsx
> +		if (["principal", "financingFee", "timeToMaturity", "repaymentType"].includes(changedValue)) {
I think you already know what I'm going to say :D turn field keys into an enum so we don't repeat hardcoded string values

2022-07-20 13:24 UTC, RuvendeGroote commented on src/components/DealForm.tsx
> +			calculateAprs(allValues);
add return statement

2022-07-20 13:24 UTC, RuvendeGroote commented on src/components/DealForm.tsx
> +		if (trancheSettingsFields.find((field) => field === changedValue)) {
use include

2022-07-20 13:24 UTC, RuvendeGroote commented on src/components/DealForm.tsx
> +		const changedValue = Object.keys(changedValues)[0];
rename to formItemKey

2022-07-20 13:24 UTC, RuvendeGroote commented on src/components/DealForm.tsx
> +	const onValuesChange = (changedValues, allValues) => {
add comments because it is quite hard to read without any type information to jump around with

2022-07-20 13:24 UTC, RuvendeGroote commented on src/components/TrancheSelectionOption.tsx
> +												name={[tranche.value, t.name, "percentageOfPrincipal"]}
also here

2022-07-20 13:24 UTC, RuvendeGroote commented on src/components/TrancheSelectionOption.tsx
> +														required: true,
maybe a nice function like:
```
const required = (msg: MessageDescriptor) => ({ required: true, message: intl.formatMessage(msg)})
```
then we can just do:
```
required(MESSAGES.percentageOfInterestRequiredValidation)
```
which is a little more compact than what have now.

2022-07-20 13:24 UTC, RuvendeGroote commented on src/consts.ts
>  export type DealTrancheSettings = {
I don't like this type. one two three tranche structures will still have senior, mezzanine and junior settings. this doesn't reflect what is actually the case. it might be more convenient when setting up the type but you will be fighting it wherever you use it

2022-07-20 13:24 UTC, RuvenSalamon commented on src/utils/format.utils.ts
> +export const compactRatioFormatter = (n: BigSource) =>
no test

2022-07-20 15:40 UTC, BartDeCaluwe commented on src/consts.ts
>  export type DealTrancheSettings = {
I'm not sure that I fully understand what you're saying.

2022-07-20 15:54 UTC, RuvenSalamon commented on src/consts.ts
>  export type DealTrancheSettings = {
OneTrancheStructure also has Mezzanine and Junior TrancheSettings. It should not. The typings should reflect this instead of how it is now.

2022-07-22 02:00 UTC, RuvenSalamon reviewed
let's do some pair programming tomorrow. I have a stash ready to take a look at.

2022-07-22 15:41 UTC, RuvenSalamon approved these changes

2022-07-22 15:41 UTC, RuvendeGroote commented on src/components/DealForm.tsx
> +	const onThreeTrancheSeniorPOIChange = () => {
add comments explaining complexity, 'dangers' and business logic

2022-07-22 15:43 UTC, merged