Pool statistics
credix-finance/credix-app-v2 pull request #26
Opened 2022-02-23 12:37 UTC by BartDeCaluwe

This PR will add:

- Config with the ability to specify the `clusterTarget` as an env var based on the config file of the v1 of the app.
- Integration with the `@credix/credix-client` package
- MarketStats component
- Updates to the `Statistics` component as they now expect the `value` prop to be either a `Big` or a `Ratio`
- formatting utils snatched from the v1

2022-02-28 12:34 UTC, BouweCeunen commented on src/types/solana.types.ts
> +export type PdaSeeds = Array<Buffer | Uint8Array>;
Is this already used somewhere?

2022-02-28 12:34 UTC, BouweCeunen commented on src/pages/index.tsx
> +	const [market, setMarket] = useState<Market | null>(null);
Small thing, maybe not needed to pass in default value `null`?

2022-02-28 12:34 UTC, BouweCeunen commented on src/components/ClientProvider.tsx
> +			wallet={wallet as typeof Wallet}
Is `Wallet` imported somewhere?

2022-02-28 12:34 UTC, BouweCeunen commented on src/config.ts
> +	gatewayProgramId: new PublicKey("gatem74V238djXdzWnJf94Wo1DcnuGkfijbf3AuBhfs"),
Best to just hardcode these 2 values because they are the same accross all environments.

2022-02-28 14:42 UTC, BartDeCaluwe commented on src/types/solana.types.ts
> +export type PdaSeeds = Array<Buffer | Uint8Array>;
Nope, you're right. Deleted it.

2022-03-01 09:34 UTC, BouweCeunen submitted a review, later dismissed

2022-03-02 09:39 UTC, RuvenSalamon requested changes

2022-03-02 09:39 UTC, RuvenSalamon commented on src/components/Statistic.tsx
> +	const formattedValue = useMemo(() => {
have the user of this component supply the value as a number

2022-03-03 10:23 UTC, RuvenSalamon approved these changes

2022-03-03 10:26 UTC, BouweCeunen approved these changes

2022-03-03 10:27 UTC, merged