Integrate civic 0.4.13
credix-finance/credix-app-v2 pull request #30
Opened 2022-02-24 14:38 UTC by BartDeCaluwe

This PR will add:

- Civic 0.4.13 integration
- Basic styling of the civic button
- renamed REACT_APP_CLUSTER to NEXT_PUBLIC_REACT_APP_CLUSTER as otherwise nextjs cant read it.

@BouweCeunen I'm assuming that the env var rename has some consequences for our infra?

2022-03-03 10:30 UTC, RuvendeGroote commented on .github/workflows/cicd.yaml
> +          NEXT_PUBLIC_BASE_PATH= NEXT_PUBLIC_REACT_APP_CLUSTER=devnet yarn build
remove NEXT_PUBLIC_BASE_PATH

2022-03-03 10:30 UTC, RuvenSalamon commented on .github/workflows/cicd.yaml
> +          NEXT_PUBLIC_BASE_PATH= NEXT_PUBLIC_REACT_APP_CLUSTER=mainnet yarn build
same

2022-03-03 11:11 UTC, RuvendeGroote commented
investigate the many rerenders and  duplicate rpc calls

2022-03-04 10:16 UTC, RuvenSalamon commented
add info about targetting the right cluster to the readme.
add info about that we use the civic pass (only on devnet) to readme

2022-03-04 10:22 UTC, RuvenSalamon commented on src/components/Identity.tsx
> +export const Identity = () => {
Rename to civicprovider (same principle as you did with the clientprovider)

2022-03-04 10:26 UTC, RuvenSalamon commented on src/components/Identity.tsx
> +export const Identity = () => {
rename to CivicButton

2022-03-04 10:33 UTC, RuvenSalamon requested changes

2022-03-04 10:33 UTC, RuvenSalamon commented on src/pages/index.tsx
> +	}, []);
add a comment explaining why we ignore the eslint warning here and why getmarket should not be added as a dependency again

2022-03-04 10:33 UTC, RuvenSalamon commented on src/config.ts
> +	stage: CivicStage.LOCALNET,
this doesn't need to be part of the config. it's very specific for a particular component and can easily be derived from the cluster in the config already.

2022-03-15 09:08 UTC, BouweCeunen submitted a review, later dismissed

2022-03-15 09:57 UTC, RuvenSalamon requested changes

2022-03-15 09:57 UTC, RuvenSalamon commented on src/components/IdentityButton.tsx
> +		const market = await client.fetchMarket(defaultMarketplace);
can we use the market from the state here?

2022-03-15 13:16 UTC, RuvenSalamon approved these changes

2022-03-15 13:18 UTC, BouweCeunen approved these changes

2022-03-15 13:19 UTC, merged