Screen 4 active deal
credix-finance/credix-app-v2 pull request #36
Opened 2022-03-03 18:12 UTC by BartDeCaluwe

2022-03-21 10:05 UTC, RuvenSalamon commented
![image](https://user-images.githubusercontent.com/14349484/159240129-37c9b35c-4b4d-49a9-a392-3614d0b0ee9b.png)
this looks weird

2022-03-21 10:11 UTC, RuvenSalamon commented
when fetching the deals we preform the same call a lot
![image](https://user-images.githubusercontent.com/14349484/159240963-3eed0fd0-bc87-4146-9cad-88671a175389.png)

2022-03-21 10:11 UTC, RuvenSalamon commented
> when fetching the deals we preform the same call a lot ![image](https://user-images.githubusercontent.com/14349484/159240963-3eed0fd0-bc87-4146-9cad-88671a175389.png)

![image](https://user-images.githubusercontent.com/14349484/159241050-bce01135-c96b-4c99-bad5-f3ec0731b048.png)

2022-03-21 10:57 UTC, RuvenSalamon requested changes

2022-03-21 10:57 UTC, RuvendeGroote commented on src/utils/format.utils.ts
> +export const clamp = (value: number, min: number, max: number) => {
we can write tests for stuff like this (or use the lodash clamp function)

2022-03-21 10:57 UTC, RuvendeGroote commented on src/utils/format.utils.ts
> +export const numberFormatter = Intl.NumberFormat("en", {
same here, utils like this can be tested

2022-03-21 10:57 UTC, RuvendeGroote commented on src/utils/format.utils.ts
why is the fallback n-GB below?

2022-03-21 10:57 UTC, RuvendeGroote commented on src/utils/format.utils.ts
>  export const formatRatio = (r: Ratio) => {
this can be implemented on the Ratio class itself

2022-03-21 10:57 UTC, RuvendeGroote commented on src/state/marketSlice.ts
> +	activeDeals?: Deal[];
the deal state arrays can be selectors on alldeals
I think we should move to separate selector files anyways

2022-03-21 10:57 UTC, RuvendeGroote commented on src/state/marketSlice.ts
> +const getMarket = (client: CredixClient, marketPlace: string) => {
this function doesn't add much

2022-03-21 10:57 UTC, RuvendeGroote commented on src/state/marketSlice.ts
> +	const market = get().market ? get().market : await getMarket(client, marketPlace);
if we just do a maybefetch market we can then do a get afterwards and it will have the same logic but more readable and concise

2022-03-21 10:57 UTC, RuvendeGroote commented on src/state/marketSlice.ts
> +	set({ isLoadingDeals: true });
can we put the isLoadingDeals in the getDeals function?

2022-03-21 10:57 UTC, RuvendeGroote commented on src/state/marketSlice.ts
> +	set({ allDeals, activeDeals, endedDeals, pendingDeals, isLoadingDeals: false });
same here

2022-03-21 10:57 UTC, RuvendeGroote commented on src/state/marketSlice.ts
>  	fetchMarket: async (client, marketPlace) => {
put these functions as consts somewhere so they don't clutter this object so much

2022-03-21 10:57 UTC, RuvendeGroote commented on src/state/marketSlice.ts
>  	fetchMarket: async (client, marketPlace) => {
also, we don't use fetchMarket it seems so let's remove it

2022-03-21 10:57 UTC, RuvendeGroote commented on src/state/marketSlice.ts
> +	fetchDeals: async (client, marketPlace) => {
also not used it seems

2022-03-21 10:57 UTC, RuvendeGroote commented on src/state/marketSlice.ts
> +			return;
do we expect the deal to exist here? if so I would fail hard. I don't like silent failures because it hides bugs

2022-03-21 10:57 UTC, RuvendeGroote commented on src/pages/[marketplace]/index.tsx
> +import Link from "next/link";
double import

2022-03-21 10:57 UTC, RuvenSalamon commented on src/pages/[marketplace]/deals.tsx
>  const Deals: NextPage = () => {
add layout

2022-03-21 10:57 UTC, RuvenSalamon commented on src/pages/[marketplace]/deals.tsx
> +	const [isAdmin, setIsAdmin] = useState<boolean>(false);
either use state per component or use the zustand admin state

2022-03-21 10:57 UTC, RuvenSalamon commented on src/state/marketSlice.ts
> +import { GetState, SetState } from "zustand";
add tests

2022-03-21 11:48 UTC, BartDeCaluwe commented on src/utils/format.utils.ts
No particular reason, we just need **a** fallback. Would you rather have it be "en-US"?

2022-03-24 14:56 UTC, BartDeCaluwe commented on src/utils/format.utils.ts
>  export const formatRatio = (r: Ratio) => {
We actually might not even need this code. We can use `Ratio.apply` here.

2022-03-28 07:53 UTC, BouweCeunen commented
<img width="829" alt="image" src="https://user-images.githubusercontent.com/5576686/160351801-55a270f9-617b-4698-9e33-b6928381a972.png">
following Figma, left should be `0%` instead of just a `0` maybe? Also not sure what the `0` is on the right with "time left".

2022-03-28 12:15 UTC, RuvenSalamon commented
conflicts

2022-03-29 07:28 UTC, RuvenSalamon commented on __tests__/__mocks__/zustand.ts
> +	storeResetFns.add(() => store.setState(initialState, true));
we don't have multiple stores right now as far as I know so no point in an elaborate setup to support them. KISS

2022-03-29 08:11 UTC, RuvendeGroote commented on __tests__/__mocks__/zustand.ts
> +const storeResetFns = new Set();
we don't have multiple stores right now as far as I know so no point in an elaborate setup to support them. KISS

2022-03-29 08:11 UTC, RuvendeGroote commented on __tests__/__mocks__/zustand.ts
> +const storeResetFns = new Set();
+ WAGNI!

2022-03-29 08:11 UTC, RuvendeGroote commented on src/components/DealStatus.tsx
> +	deal?: Deal;
why is this optional? it's only used in a place where there is always a deal

2022-03-29 08:11 UTC, RuvendeGroote commented on src/components/DealDetails.tsx
> +			toUIAmount(deal?.principalAmountRepaid).toNumber(),
deal always exists

2022-03-29 08:11 UTC, RuvendeGroote commented on src/components/DealAspect.tsx
> +	showRatio?: boolean;
is there a case where we have a ratio but don't show it? or is there a reason why we would want to pass a ratio but not show it? showRatio and ratio seem tightly coupled right now so just use ratio

2022-03-29 08:11 UTC, RuvendeGroote commented on src/components/DealAspect.tsx
> +	ratio?: number;
just accept a Ratio here

2022-03-29 08:11 UTC, RuvendeGroote commented on src/components/DealDetails.tsx
> +	const [interestRepaidRatio, setInterestRepaidRatio] = useState<number | 0>();
use Ratio here

2022-03-29 08:11 UTC, RuvendeGroote commented on src/components/DealDetails.tsx
> +		if (deal?.interestToRepay.eq(new Big(0))) {
if you use the ratio interestRepaid/totalInterest it will be 1 if everything is repaid and this logic can be simplified

2022-03-29 08:11 UTC, RuvenSalamon commented on src/components/DealDetails.tsx
> +		if (deal?.principalAmountRepaid) {
we don't show it so don't need it

2022-03-29 08:25 UTC, BartDeCaluwe commented on src/components/DealAspect.tsx
> +	showRatio?: boolean;
The ratio is used for both the rendering of the "progress bar" and just displaying the formatted value. In the case of the amount of days left, only the progress bar is displayed, not the actual value. Hence, the distinction.

2022-03-29 08:49 UTC, RuvenSalamon requested changes

2022-03-29 08:49 UTC, RuvenSalamon commented on src/state/marketSlice.ts
>  	fetchMarket: async (client, marketPlace) => {
this still applies

2022-03-29 09:26 UTC, RuvendeGroote requested changes

2022-03-29 09:26 UTC, RuvenSalamon commented on src/components/DealStatus.tsx
> +	if (!deal) {
if deal is not optional this check is also no longer required

2022-03-29 09:26 UTC, RuvendeGroote commented on src/components/DealAspect.tsx
> +					style={{ width: `${clamp(ratio.apply(new Big(1)).toNumber() * 100, 0, 100)}%` }}
if this is something you feel could be useful to in the Ratio class itself you can always propose it. it's basically `toPercentage()` or something

2022-03-29 10:42 UTC, RuvenSalamon requested changes

2022-03-29 10:42 UTC, RuvenSalamon commented on src/state/dealSlice.ts
> +	fetchDeals: (market) => getDeals(market, set),
getDeals doesn't return `Promise<void>`

2022-03-29 10:55 UTC, BartDeCaluwe commented on src/components/DealAspect.tsx
> +					style={{ width: `${clamp(ratio.apply(new Big(1)).toNumber() * 100, 0, 100)}%` }}
Yes, IMO could be useful!

2022-03-29 11:15 UTC, RuvenSalamon approved these changes

2022-03-29 11:27 UTC, BouweCeunen approved these changes

2022-03-29 11:28 UTC, merged