feat: equalise button and logo spacing and give them a bit more breathing room
credix-finance/credix-app-v2 pull request #40
Opened 2022-03-18 11:07 UTC by BartDeCaluwe

2022-03-21 13:50 UTC, RuvenSalamon requested changes
can we center the logo vertically? but I will follow majority vote on this one

2022-03-24 10:24 UTC, BouweCeunen commented
> can we center the logo vertically? but I will follow majority vote on this one

Indeed, seems that a `vertical-align: middle` could be enough, but if it takes too long it's also not that important for me.

2022-03-25 13:35 UTC, RuvenSalamon submitted a review, later dismissed

2022-03-28 07:54 UTC, BouweCeunen approved these changes, later dismissed

2022-03-28 13:13 UTC, RuvenSalamon approved these changes

2022-03-28 13:15 UTC, BouweCeunen approved these changes

2022-03-28 13:16 UTC, merged